// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CodeHighlightController from "./code_highlight_controller"
application.register("code-highlight", CodeHighlightController)
