require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/waitlist/users", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Waitlist::User. As you add validations to Waitlist::User, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    attributes_for(:waitlist_user)
  }

  let(:invalid_attributes) {
    attributes_for(:invalid_waitlist_user)
  }

  describe "GET /new" do
    it "renders a successful response" do
      get new_waitlist_user_url
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Waitlist::User" do
        expect {
          post waitlist_users_url, params: { waitlist_user: valid_attributes }
        }.to change(Waitlist::User, :count).by(1)
      end

      it "redirects to the created waitlist_user" do
        post waitlist_users_url, params: { waitlist_user: valid_attributes }
        expect(response).to redirect_to(app_index_url)
      end
    end

    context "with invalid parameters" do
      it "does not create a new Waitlist::User" do
        expect {
          post waitlist_users_url, params: { waitlist_user: invalid_attributes }
        }.to change(Waitlist::User, :count).by(0)
      end

    
      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post waitlist_users_url, params: { waitlist_user: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    
    end
  end

end
